<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Жожа-ПК" name="myApplicationTest.TestNameIDGroup" tests="4" failures="1" timestamp="15 Jul 2015 16:38:36 GMT" time="0.071" errors="0">
  <testcase name="EmployeeTest_A" time="0.061" classname="myApplicationTest.TestNameIDGroup"/>
  <testcase name="EmployeeTest_B" time="0.010" classname="myApplicationTest.TestNameIDGroup"/>
  <testcase name="EmployeeTest_D" time="0.000" classname="myApplicationTest.TestNameIDGroup">
    <failure type="java.lang.AssertionError" message="expected [1001] but found [100001]">
      <![CDATA[java.lang.AssertionError: expected [1001] but found [100001]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:492)
	at org.testng.Assert.assertSame(Assert.java:443)
	at org.testng.Assert.assertSame(Assert.java:453)
	at myApplicationTest.TestNameIDGroup.EmployeeTest_D(TestNameIDGroup.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- EmployeeTest_D -->
  <testcase name="EmployeeTest_C" time="0.000" classname="myApplicationTest.TestNameIDGroup"/>
</testsuite> <!-- myApplicationTest.TestNameIDGroup -->
